---
title: "Ce qui rend R unique : 5 fonctionnalités qui séduisent un développeur Python"
author:
  - Joseph Barbier^[Yellow Sunflower, joseph@ysunflower.com]
format: typst
indent: true
lang: fr
---

```{=typst}
#align(center)[#strong[Résumé]]
```

R possède de nombreuses particularités qui peuvent sembler étranges pour un développeur Python, mais qui rendent le langage particulièrement puissant et expressif. Dans cette présentation, je montrerai 5 fonctionnalités que j'apprécie particulièrement et qui peuvent transformer la manière de coder en R.

Nous verrons comment créer des opérateurs personnalisés pour rendre votre code plus lisible, surcharger des fonctions pour des objets spécialisés, utiliser la métaprogrammation pour analyser et transformer des expressions, tirer parti du système S3 pour une approche simple de la programmation orientée objet et profiter de la lazy evaluation pour définir des arguments par défaut intelligents et dynamiques.

Cette présentation s'adresse à n'importe quel utilisateur de R, débutant ou non, qui souhaitent mieux comprendre ce qui fait la singularité du langage. L'objectif est également de montrer aux utilisateurs plus débutants que ce qu'on appelle "utilisation avancée" n'a pas à être complexe.

**Mots-clés (3 à 5)** : S3 - Métaprogrammation - Lazy Evaluation - Syntaxe

## Développement

### Partie 1 - Apprendre R depuis Python

Dans cette partie, j’expliquerai ce qu’il se passe lorsque l’on décide d’apprendre le langage R, notamment lorsque l’on utilise déjà Python.

### Partie 2 - Cinq mécanismes qui changent la façon de coder en R

- Créer ses propres opérateurs

- Surcharge d'opérateurs

- Métaprogrammation avec `substitute()`

- Méthodes S3 et fonctions génériques

- Arguments par défaut dépendants
